CREATE TABLE `output`.`CurrentMedication` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NULL DEFAULT NULL,
  `pillName` VARCHAR(245) NULL DEFAULT NULL,
  `date_prescribed` DATE NULL DEFAULT NULL,
  `dailyDosage` INT NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
  ENGINE=InnoDB DEFAULT CHARSET=latin1;