CREATE TABLE City(
    `id` int(11) NOT NULL AUTO_INCREMENT, 
    `cityName` varchar(45) DEFAULT NULL, 
    `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
   `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
    
)ENGINE=InnoDB DEFAULT CHARSET=latin1;